4 new function download media
inbo/fistools pull request #6
Opened 2024-04-26 15:43 UTC by SanderDevisscher

fixes #4 

Om te testen:
```
devtools::instal_github("fistools@4-new-function-download_media")

fistools::download_media()
```

2024-04-29 06:57 UTC, LynnPallemaerts commented
@SanderDevisscher Wil wel reviewen, maar hierboven staat "All checks have failed". Maakt dat uit voor de review?

2024-04-29 07:42 UTC, SanderDevisscher commented
Ok ze falen nu op de scafolding

2024-05-02 09:29 UTC, soriadelva commented on R/download_media.R
Zou het kunnen dat deze file niet bestaat (of op een andere locatie te vinden is)?: "./Grofwild/Drongengoed/Input/Agouti/drongengoed_230601.zip"

2024-05-02 09:31 UTC, SanderDevisscher commented on R/download_media.R
file bestaat idd niet in deze repo. @LynnPallemaerts kan jij de file bezorgen ? En kort beschrijven hoe en waar je die gehaald hebt ? 

Ik zal het dan in de details toevoegen.

2024-05-02 19:02 UTC, SanderDevisscher commented
I should add `#' @export`

2024-05-08 14:22 UTC, soriadelva requested changes
I'll wait to approve until the example data are added to the Agouti folder so it can be tested. In the meantime, should the outputfolder path in the examples be changed to something more generic? Atm it is outputfolder = "C:/Users/lynn_pallemaerts/Pictures

2024-05-14 09:14 UTC, SanderDevisscher commented on R/download_media.R
> +  for (i in 1:nrow(med)) {
@LynnPallemaerts add progress bar

2024-05-14 09:14 UTC, SanderDevisscher commented on R/download_media.R
> +    }
add askyesno if aantal foto's > 500

2024-05-14 09:14 UTC, SanderDevisscher commented on R/download_media.R
> +                           location,
Add deploymentID as parameter

2024-05-27 14:52 UTC, SanderDevisscher commented
De authors need more indentation I think 😅

2024-05-27 15:27 UTC, LynnPallemaerts commented
> De authors need more indentation I think 😅

Why is this even an issue ? 😅

2024-05-27 15:30 UTC, SanderDevisscher commented
> > De authors need more indentation I think 😅
> 
> Why is this even an issue ? 😅

Some coding languages rely on indentation rather than (, { or [ while other use ( for everything (looking at you lisp)

![image](https://github.com/inbo/fistools/assets/16779320/3cad2f84-cf9e-4935-83b4-f9d8182b897a)

2024-05-27 17:26 UTC, soriadelva approved these changes

2024-05-28 07:50 UTC, merged